version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
      - ./data/postgres16:/var/lib/postgresql/data
    env_file:
      - ./.env.local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - ./.env.local
