version: '3.9'

services:
  postgres_test:
    image: postgres:16.1-alpine
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres16_test:/var/lib/postgresql/data
    env_file:
      - ./.env.test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis_test:
    image: redis:7.0-alpine
    ports:
      - 6380:6379
    volumes:
      - ./data/redis_test:/data
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - ./.env.test
